In [117]:
!nvidia-smi

zsh:1: command not found: nvidia-smi


In [118]:
!pip install missingpy

In [119]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import roc_auc_score
import math

In [120]:
import sklearn.neighbors._base
sys.modules['sklearn.neighbors.base'] = sklearn.neighbors._base

In [121]:
import sys
import numpy as np
import pandas as pd

from missingpy import MissForest
from dsan import Imputer as DSANImputer
from utils import *

import warnings
warnings.filterwarnings('ignore')

In [122]:
seed = 128
set_seed(seed)

In [123]:
def get_imputer(config):
    
    model = config['model']
    
    if model == 'DSAN':
        imputer = DSANImputer(rep_dim=config['rep_dim'],
                num_heads=config['num_heads'],
                n_hidden=config['n_hidden'],
                lr=config['lr'],
                weight_decay=config['weight_decay'],
                batch_size=config['batch_size'],
                epochs=config['epochs'],
                noise_percent=config['noise_percent'],
                stopped_epoch=config['stopped_epoch'])
    
    elif model == 'MissForest':
        imputer = MissForest(random_state=0)
        
    elif model == 'Statistics':
        imputer = None
        
    return imputer

In [124]:
'''def experiment_run(data_name, config, test=False):
    
    # Retrieve dataset
    dataset = get_data(data_name)
    print(f"Retrieved dataset for {data_name}")

    # Limit to 1000 samples if test flag is true
    if test:
        dataset = (dataset[0][:1000], dataset[1], dataset[2], dataset[3])
        print("Limited dataset to 1000 samples for testing")

    k = 5
    percent_missing_lst = [p for p in range(5, 25, 5)]    
    X_origin, n_col, num_vars, cat_vars = dataset

    # Apply category mapping
    X_origin = category_mapping(X_origin, cat_vars)
    print("Applied category mapping")

    # Print data size
    print("Data Size: {}".format(X_origin.shape))

    n_sample = X_origin.shape[0]
    idx_lst = list(range(n_sample))
    np.random.shuffle(idx_lst)

    # k-fold validation setup
    n_valid = len(idx_lst) // k
    print(f"Starting k-fold validation with k={k}")

    results = {}
    for percent_missing in percent_missing_lst:
        result = []
        print(f"\nProcessing {percent_missing}% missing data")

        for it, n in enumerate(range(0, n_sample, n_valid)):
            print(f"\nFold {it + 1}")
            valid_idx = idx_lst[n: n+n_valid]

            if len(valid_idx) < n_valid:
                print("Insufficient data for validation, breaking loop")
                break

            train_idx = list(set(idx_lst) - set(valid_idx))
            X = X_origin[train_idx, :]
            X_test = X_origin[valid_idx, :]

            # Generating incomplete data
            missing_mask = generate_missing_mask(X, percent_missing=percent_missing)
            X_incomplete = X.copy()
            X_incomplete[missing_mask] = np.nan
            print("Generated incomplete data with missing values")

            # Imputation
            imputer = get_imputer(config)
            X_imputed = imputer.fit_transform(X_incomplete, cat_vars=cat_vars)
            print("Completed imputation")
            
            # Print a small subset of original and imputed data for comparison
            print("Original data with missing values (subset):")
            print(X_incomplete[:5])  # Adjust the number of rows as needed
            #print("Imputed data (subset):")
            #print(X_imputed[:5])  # Adjust the number of rows as needed


            X_res = X.copy()
            X_res[missing_mask] = X_imputed[missing_mask]
            
            print("X_res with imputed values (subset):")
            print(X_res[:5]) 

            # Calculate metrics
            metric = cal_metric_numpy(X_res, X, missing_mask, num_vars, cat_vars)
            score = ex_classify(data_name=data_name, train_array=X_res, test_array=X_test, num_vars=num_vars, cat_vars=cat_vars)
            
            metric['clf_aucroc'] = round(score, 4)
            result.append(metric)
            print("Metrics for this fold:", metric)

        # Average results
        avg_result = dict()
        for key in result[0].keys():
            value = np.mean([m[key] for m in result])
            avg_result[key] = value 
            print(f"Average {key} for {percent_missing}% missing data: {value}")

        results[percent_missing] = avg_result

    print("Completed all iterations")
    return results
'''

'def experiment_run(data_name, config, test=False):\n    \n    # Retrieve dataset\n    dataset = get_data(data_name)\n    print(f"Retrieved dataset for {data_name}")\n\n    # Limit to 1000 samples if test flag is true\n    if test:\n        dataset = (dataset[0][:1000], dataset[1], dataset[2], dataset[3])\n        print("Limited dataset to 1000 samples for testing")\n\n    k = 5\n    percent_missing_lst = [p for p in range(5, 25, 5)]    \n    X_origin, n_col, num_vars, cat_vars = dataset\n\n    # Apply category mapping\n    X_origin = category_mapping(X_origin, cat_vars)\n    print("Applied category mapping")\n\n    # Print data size\n    print("Data Size: {}".format(X_origin.shape))\n\n    n_sample = X_origin.shape[0]\n    idx_lst = list(range(n_sample))\n    np.random.shuffle(idx_lst)\n\n    # k-fold validation setup\n    n_valid = len(idx_lst) // k\n    print(f"Starting k-fold validation with k={k}")\n\n    results = {}\n    for percent_missing in percent_missing_lst:\n        resul

In [126]:
def experiment_run(data_name, config, test=False):
    # Retrieve dataset
    dataset = get_data(data_name)
    print(f"Retrieved dataset for {data_name}")

    # Limit to 1000 samples if test flag is true
    if test:
        dataset = (dataset[0][:1000], dataset[1], dataset[2], dataset[3])
        print("Limited dataset to 1000 samples for testing")

    k = 5
    percent_missing_lst = [p for p in range(5, 25, 5)]
    X_origin, n_col, num_vars, cat_vars = dataset

   # Apply category mapping
    X_origin = category_mapping(X_origin, cat_vars)
    print("Applied category mapping")

    # Check if X_origin is modified in-place or replaced
    if X_origin is not None:
        print("X_origin is replaced with a new version where categorical variables have been mapped to numerical values.")
    else:
        print("X_origin is modified in-place, with categorical variables mapped to numerical values.")

    # Print data size
    print("Data Size: {}".format(X_origin.shape))


    n_sample = X_origin.shape[0]
    idx_lst = list(range(n_sample))
    np.random.shuffle(idx_lst)

    # k-fold validation setup
    n_valid = len(idx_lst) // k
    print(f"Starting k-fold validation with k={k}")

    results = {}
    for percent_missing in percent_missing_lst:
        result = []
        print(f"\nProcessing {percent_missing}% missing data")

        for it, n in enumerate(range(0, n_sample, n_valid)):
            print(f"\nFold {it + 1}")
            valid_idx = idx_lst[n: n+n_valid]

            if len(valid_idx) < n_valid:
                print("Insufficient data for validation, breaking loop")
                break

            train_idx = list(set(idx_lst) - set(valid_idx))
            X = X_origin[train_idx, :]
            X_test = X_origin[valid_idx, :]

            # Generating incomplete data
            missing_mask = generate_missing_mask(X, percent_missing=percent_missing)
            X_incomplete = X.copy()
            X_incomplete[missing_mask] = np.nan
            print("Generated incomplete data with missing values for fold {}:".format(it+1))
            print("Original data with missing values (subset):")
            print(X_incomplete[:5])  # Adjust the number of rows as needed

            # Imputation
            imputer = get_imputer(config)
            X_imputed = imputer.fit_transform(X_incomplete, cat_vars=cat_vars)
            print("Completed imputation for fold {}:".format(it+1))

            X_res = X.copy()
            X_res[missing_mask] = X_imputed[missing_mask]
            print("X_res with imputed values (subset):")
            print(X_res[:5])  # Adjust the number of rows as needed

            # Calculate metrics
            metric = cal_metric_numpy(X_res, X, missing_mask, num_vars, cat_vars)
            score = ex_classify(data_name=data_name, train_array=X_res, test_array=X_test, num_vars=num_vars, cat_vars=cat_vars)
            
            metric['clf_aucroc'] = round(score, 4)
            result.append(metric)
            print("Metrics for this fold:", metric)

        # Average results
        avg_result = dict()
        for key in result[0].keys():
            value = np.mean([m[key] for m in result])
            avg_result[key] = value 
            print(f"Average {key} for {percent_missing}% missing data: {value}")

        results[percent_missing] = avg_result

    print("Completed all iterations")
    return results


In [127]:
config = {
    'model': 'DSAN',
    'rep_dim': 32,
    'num_heads': 8,
    'n_hidden': 2,
    'lr': 3e-3,
    'weight_decay': 1e-5,
    'batch_size': 128,
    'epochs': 15,
    'noise_percent': 10,
    'stopped_epoch': 10
}

In [128]:
import missingpy
from missingpy import MissForest

In [129]:
data_name_lst = ['adult']

result_dir = './results1'
os.makedirs(result_dir)

for data_name in data_name_lst:
    results = experiment_run(data_name, config, test=True)
    results['config'] = config
    results['dataset'] = data_name
    result_path = os.path.join(result_dir, '{}.json'.format(data_name))
    write_json(results, result_path)

Retrieved dataset for adult
Limited dataset to 1000 samples for testing
Applied category mapping
X_origin is replaced with a new version where categorical variables have been mapped to numerical values.
Data Size: (1000, 15)
Starting k-fold validation with k=5

Processing 5% missing data

Fold 1
Generated incomplete data with missing values for fold 1:
Original data with missing values (subset):
[[41 0 264663 2 10 nan nan 2 0 0 nan 3900 40 0 0]
 [38 0 150601 3 6 2 4 1 0 1 0 nan 40 0 0]
 [74 1 88638 4 16 3 2 3 0 0 nan 3683 20 0 1]
 [68 2 422013 0 9 1 nan 0 0 0 0 3683 40 0 0]
 [38 3 nan 5 15 3 2 0 0 nan 0 2824 45 0 1]]


100%|███████████████████████████████████████████| 15/15 [00:14<00:00,  1.03it/s]


Completed imputation for fold 1:
X_res with imputed values (subset):
[[41 0 264663 2 10 4 2 2 0 0 0.42824387550354004 3900 40 0 0]
 [38 0 150601 3 6 2 4 1 0 1 0 2021.291259765625 40 0 0]
 [74 1 88638 4 16 3 2 3 0 0 -1.2451661825180054 3683 20 0 1]
 [68 2 422013 0 9 1 3 0 0 0 0 3683 40 0 0]
 [38 3 136020.734375 5 15 3 2 0 0 0 0 2824 45 0 1]]
Metrics for this fold: {'nrmse': 0.3958, 'col_1_error_rate': 0.425, 'col_3_error_rate': 0.1628, 'col_5_error_rate': 0.2308, 'col_6_error_rate': 0.6667, 'col_7_error_rate': 0.1316, 'col_8_error_rate': 0.0513, 'col_9_error_rate': 0.0385, 'col_13_error_rate': 0.0435, 'col_14_error_rate': 0.0789, 'total_error_rate': 0.1818, 'clf_aucroc': 0.8556}

Fold 2
Generated incomplete data with missing values for fold 2:
Original data with missing values (subset):
[[82 0 132870 0 9 0 0 0 0 0 0 4356 18 0 0]
 [54 0 140359 1 4 1 1 1 0 0 0 3900 40 0 0]
 [41 0 264663 2 10 nan 2 2 0 0 0 3900 40 0 0]
 [34 0 216864 0 9 1 nan 1 0 0 0 3770 45 0 0]
 [38 0 150601 3 6 2 4 1 0 

100%|███████████████████████████████████████████| 15/15 [00:13<00:00,  1.09it/s]


Completed imputation for fold 2:
X_res with imputed values (subset):
[[82 0 132870 0 9 0 0 0 0 0 0 4356 18 0 0]
 [54 0 140359 1 4 1 1 1 0 0 0 3900 40 0 0]
 [41 0 264663 2 10 3 2 2 0 0 0 3900 40 0 0]
 [34 0 216864 0 9 1 9 1 0 0 0 3770 45 0 0]
 [38 0 150601 3 6 2 4 1 0 1 0 3770 40 0 0]]
Metrics for this fold: {'nrmse': 0.5191, 'col_1_error_rate': 0.3235, 'col_3_error_rate': 0.5, 'col_5_error_rate': 0.2791, 'col_6_error_rate': 0.5135, 'col_7_error_rate': 0.1667, 'col_8_error_rate': 0.0667, 'col_9_error_rate': 0.1579, 'col_13_error_rate': 0.0526, 'col_14_error_rate': 0.0811, 'total_error_rate': 0.233, 'clf_aucroc': 0.8996}

Fold 3
Generated incomplete data with missing values for fold 3:
Original data with missing values (subset):
[[82 0 132870 0 9 0 0 0 0 0 0 4356 18 0 0]
 [nan 0 140359 1 4 1 1 1 0 0 0 3900 40 0 0]
 [41 0 264663 2 10 2 2 2 0 0 0 3900 40 0 0]
 [34 0 216864 0 9 1 3 1 0 0 0 3770 45 0 0]
 [38 0 150601 3 6 nan 4 1 0 nan 0 3770 40 0 0]]


100%|███████████████████████████████████████████| 15/15 [00:14<00:00,  1.04it/s]


Completed imputation for fold 3:
X_res with imputed values (subset):
[[82 0 132870 0 9 0 0 0 0 0 0 4356 18 0 0]
 [41.68035888671875 0 140359 1 4 1 1 1 0 0 0 3900 40 0 0]
 [41 0 264663 2 10 2 2 2 0 0 0 3900 40 0 0]
 [34 0 216864 0 9 1 3 1 0 0 0 3770 45 0 0]
 [38 0 150601 3 6 4 4 1 0 0 0 3770 40 0 0]]
Metrics for this fold: {'nrmse': 0.5223, 'col_1_error_rate': 0.381, 'col_3_error_rate': 0.3125, 'col_5_error_rate': 0.2162, 'col_6_error_rate': 0.8298, 'col_7_error_rate': 0.1724, 'col_8_error_rate': 0.075, 'col_9_error_rate': 0.0962, 'col_13_error_rate': 0.0857, 'col_14_error_rate': 0.1944, 'total_error_rate': 0.2743, 'clf_aucroc': 0.8708}

Fold 4
Generated incomplete data with missing values for fold 4:
Original data with missing values (subset):
[[82 0 132870 0 9 0 nan 0 0 0 0 4356 18 0 0]
 [54 0 140359 1 4 1 1 1 0 0 0 3900 40 0 0]
 [41 0 264663 2 10 2 2 2 0 0 0 nan 40 0 0]
 [34 0 216864 0 9 1 3 1 0 0 0 3770 45 0 0]
 [38 0 150601 3 6 2 4 1 0 1 0 3770 40 0 0]]


100%|███████████████████████████████████████████| 15/15 [00:14<00:00,  1.02it/s]


Completed imputation for fold 4:
X_res with imputed values (subset):
[[82 0 132870 0 9 0 3 0 0 0 0 4356 18 0 0]
 [54 0 140359 1 4 1 1 1 0 0 0 3900 40 0 0]
 [41 0 264663 2 10 2 2 2 0 0 0 2073.50927734375 40 0 0]
 [34 0 216864 0 9 1 3 1 0 0 0 3770 45 0 0]
 [38 0 150601 3 6 2 4 1 0 1 0 3770 40 0 0]]
Metrics for this fold: {'nrmse': 0.5165, 'col_1_error_rate': 0.1282, 'col_3_error_rate': 0.3056, 'col_5_error_rate': 0.2778, 'col_6_error_rate': 0.6, 'col_7_error_rate': 0.1143, 'col_8_error_rate': 0.0606, 'col_9_error_rate': 0.05, 'col_13_error_rate': 0.1316, 'col_14_error_rate': 0.1795, 'total_error_rate': 0.2083, 'clf_aucroc': 0.8571}

Fold 5
Generated incomplete data with missing values for fold 5:
Original data with missing values (subset):
[[82 0 132870 0 9 nan 0 0 0 0 0 4356 18 0 0]
 [54 0 140359 1 4 1 1 1 0 0 0 nan nan 0 0]
 [34 0 216864 0 9 1 3 1 0 0 0 3770 45 0 0]
 [74 1 88638 4 16 3 2 3 0 0 0 3683 20 0 1]
 [68 2 422013 0 9 1 2 0 0 0 nan 3683 40 0 0]]


100%|███████████████████████████████████████████| 15/15 [00:13<00:00,  1.10it/s]


Completed imputation for fold 5:
X_res with imputed values (subset):
[[82 0 132870 0 9 3 0 0 0 0 0 4356 18 0 0]
 [54 0 140359 1 4 1 1 1 0 0 0 2201.376953125 42.8134651184082 0 0]
 [34 0 216864 0 9 1 3 1 0 0 0 3770 45 0 0]
 [74 1 88638 4 16 3 2 3 0 0 0 3683 20 0 1]
 [68 2 422013 0 9 1 2 0 0 0 -0.5503003597259521 3683 40 0 0]]
Metrics for this fold: {'nrmse': 0.5819, 'col_1_error_rate': 0.4516, 'col_3_error_rate': 0.1795, 'col_5_error_rate': 0.1429, 'col_6_error_rate': 0.5862, 'col_7_error_rate': 0.0857, 'col_8_error_rate': 0.0857, 'col_9_error_rate': 0.2, 'col_13_error_rate': 0.1667, 'col_14_error_rate': 0.0769, 'total_error_rate': 0.207, 'clf_aucroc': 0.8886}
Average nrmse for 5% missing data: 0.50712
Average col_1_error_rate for 5% missing data: 0.34186
Average col_3_error_rate for 5% missing data: 0.29208
Average col_5_error_rate for 5% missing data: 0.22936
Average col_6_error_rate for 5% missing data: 0.63924
Average col_7_error_rate for 5% missing data: 0.13413999999999998
Average

100%|███████████████████████████████████████████| 15/15 [00:13<00:00,  1.14it/s]


Completed imputation for fold 1:
X_res with imputed values (subset):
[[41 0 264663 2 10 2 2 2 0 0 0 3900 40 0 0]
 [38 0 150601 3 6 3 4 1 0 1 0.4176700711250305 3770 40 0 0]
 [74 1 88638 4 16 3 2 3 0 0 0 3683 20 0 1]
 [68 2 422013 0 9 1 2 0 0 0 0 3683 40 0 0]
 [38 3 164526 5 15 3 2 0 0 1 0 2006.9136962890625 45 0 1]]
Metrics for this fold: {'nrmse': 0.5028, 'col_1_error_rate': 0.3333, 'col_3_error_rate': 0.18, 'col_5_error_rate': 0.1224, 'col_6_error_rate': 0.7246, 'col_7_error_rate': 0.1923, 'col_8_error_rate': 0.0667, 'col_9_error_rate': 0.1282, 'col_13_error_rate': 0.1111, 'col_14_error_rate': 0.0698, 'total_error_rate': 0.2063, 'clf_aucroc': 0.8633}

Fold 2
Generated incomplete data with missing values for fold 2:
Original data with missing values (subset):
[[82 0 132870 0 9 0 0 0 0 0 0 4356 18 0 0]
 [54 0 140359 1 4 nan 1 1 0 nan 0 3900 40 0 0]
 [41 0 264663 2 10 2 2 2 0 0 0 3900 40 0 0]
 [34 0 216864 0 9 1 nan 1 0 0 nan 3770 45 0 0]
 [nan 0 150601 3 6 2 4 1 0 1 0 3770 40 0 0]]


100%|███████████████████████████████████████████| 15/15 [00:13<00:00,  1.09it/s]


Completed imputation for fold 2:
X_res with imputed values (subset):
[[82 0 132870 0 9 0 0 0 0 0 0 4356 18 0 0]
 [54 0 140359 1 4 4 1 1 0 0 0 3900 40 0 0]
 [41 0 264663 2 10 2 2 2 0 0 0 3900 40 0 0]
 [34 0 216864 0 9 1 7 1 0 0 0.015799224376678467 3770 45 0 0]
 [44.38090133666992 0 150601 3 6 2 4 1 0 1 0 3770 40 0 0]]
Metrics for this fold: {'nrmse': 0.4955, 'col_1_error_rate': 0.4648, 'col_3_error_rate': 0.2603, 'col_5_error_rate': 0.1184, 'col_6_error_rate': 0.6552, 'col_7_error_rate': 0.1519, 'col_8_error_rate': 0.1124, 'col_9_error_rate': 0.0854, 'col_13_error_rate': 0.0423, 'col_14_error_rate': 0.0759, 'total_error_rate': 0.2207, 'clf_aucroc': 0.8982}

Fold 3
Generated incomplete data with missing values for fold 3:
Original data with missing values (subset):
[[82 0 132870 0 9 0 0 nan 0 0 0 4356 nan 0 0]
 [54 0 140359 1 4 1 1 1 0 0 0 nan 40 0 0]
 [41 0 264663 2 10 nan nan 2 0 0 0 3900 40 0 0]
 [34 0 216864 0 9 1 nan 1 0 0 0 3770 45 0 0]
 [38 nan 150601 3 6 nan 4 1 0 1 0 3770 nan 0

100%|███████████████████████████████████████████| 15/15 [00:13<00:00,  1.11it/s]


Completed imputation for fold 3:
X_res with imputed values (subset):
[[82 0 132870 0 9 0 0 0 0 0 0 4356 45.5616569519043 0 0]
 [54 0 140359 1 4 1 1 1 0 0 0 2145.9091796875 40 0 0]
 [41 0 264663 2 10 4 4 2 0 0 0 3900 40 0 0]
 [34 0 216864 0 9 1 4 1 0 0 0 3770 45 0 0]
 [38 0 150601 3 6 3 4 1 0 1 0 3770 58.521820068359375 0 0]]
Metrics for this fold: {'nrmse': 0.4655, 'col_1_error_rate': 0.3167, 'col_3_error_rate': 0.209, 'col_5_error_rate': 0.2111, 'col_6_error_rate': 0.7447, 'col_7_error_rate': 0.1556, 'col_8_error_rate': 0.0923, 'col_9_error_rate': 0.1818, 'col_13_error_rate': 0.0563, 'col_14_error_rate': 0.1111, 'total_error_rate': 0.2449, 'clf_aucroc': 0.8761}

Fold 4
Generated incomplete data with missing values for fold 4:
Original data with missing values (subset):
[[82 0 132870 0 9 0 0 0 0 0 0 4356 nan nan 0]
 [54 0 140359 1 4 1 nan 1 0 0 0 3900 40 0 0]
 [41 nan 264663 2 10 2 2 2 0 0 0 3900 40 0 0]
 [34 0 216864 0 nan 1 3 1 0 0 0 nan 45 0 0]
 [38 0 nan 3 6 2 4 1 nan 1 0 3770 40 0

100%|███████████████████████████████████████████| 15/15 [00:14<00:00,  1.01it/s]


Completed imputation for fold 4:
X_res with imputed values (subset):
[[82 0 132870 0 9 0 0 0 0 0 0 4356 40.00960922241211 0 0]
 [54 0 140359 1 4 1 2 1 0 0 0 3900 40 0 0]
 [41 0 264663 2 10 2 2 2 0 0 0 3900 40 0 0]
 [34 0 216864 0 10.701727867126465 1 3 1 0 0 0 2163.972900390625 45 0 0]
 [38 0 211290.734375 3 6 2 4 1 0 1 0 3770 40 0 0]]
Metrics for this fold: {'nrmse': 0.4356, 'col_1_error_rate': 0.3478, 'col_3_error_rate': 0.1739, 'col_5_error_rate': 0.2273, 'col_6_error_rate': 0.7805, 'col_7_error_rate': 0.2143, 'col_8_error_rate': 0.1528, 'col_9_error_rate': 0.0909, 'col_13_error_rate': 0.0506, 'col_14_error_rate': 0.1154, 'total_error_rate': 0.2461, 'clf_aucroc': 0.8505}

Fold 5
Generated incomplete data with missing values for fold 5:
Original data with missing values (subset):
[[82 0 132870 0 9 0 0 0 0 0 0 nan 18 0 0]
 [54 0 140359 1 4 1 1 1 0 0 0 3900 40 0 0]
 [34 0 216864 nan 9 1 3 1 nan 0 nan 3770 45 nan 0]
 [74 1 88638 4 16 3 2 3 0 0 0 3683 20 0 1]
 [68 nan 422013 nan 9 1 2 0 

100%|███████████████████████████████████████████| 15/15 [00:13<00:00,  1.08it/s]


Completed imputation for fold 5:
X_res with imputed values (subset):
[[82 0 132870 0 9 0 0 0 0 0 0 2073.908935546875 18 0 0]
 [54 0 140359 1 4 1 1 1 0 0 0 3900 40 0 0]
 [34 0 216864 0 9 1 3 1 0 0 0.9836171865463257 3770 45 0 0]
 [74 1 88638 4 16 3 2 3 0 0 0 3683 20 0 1]
 [68 0 422013 0 9 1 2 0 0 0 0 3683 40 0 0]]
Metrics for this fold: {'nrmse': 0.5526, 'col_1_error_rate': 0.4167, 'col_3_error_rate': 0.2892, 'col_5_error_rate': 0.1566, 'col_6_error_rate': 0.7206, 'col_7_error_rate': 0.1765, 'col_8_error_rate': 0.0482, 'col_9_error_rate': 0.1, 'col_13_error_rate': 0.022, 'col_14_error_rate': 0.1216, 'total_error_rate': 0.2142, 'clf_aucroc': 0.881}
Average nrmse for 10% missing data: 0.4904
Average col_1_error_rate for 10% missing data: 0.37586
Average col_3_error_rate for 10% missing data: 0.22248
Average col_5_error_rate for 10% missing data: 0.16716
Average col_6_error_rate for 10% missing data: 0.72512
Average col_7_error_rate for 10% missing data: 0.17812
Average col_8_error_rate fo

100%|███████████████████████████████████████████| 15/15 [00:13<00:00,  1.12it/s]


Completed imputation for fold 1:
X_res with imputed values (subset):
[[41 0 264663 2 10 2 2 2 0 0 0 3900 40 0 0]
 [38 0 129007.59375 3 6 2 4 1 0 1 0 3770 40 0 0]
 [74 0 88638 4 16 1 2 3 0 0 0 3683 20 0 1]
 [68 2 422013 0 9 1 2 0 0 0 0 3683 40 0 0]
 [38 3 164526 5 15 3 2 0 0 0 0 2824 45 0 0]]
Metrics for this fold: {'nrmse': 0.4809, 'col_1_error_rate': 0.2941, 'col_3_error_rate': 0.3719, 'col_5_error_rate': 0.1679, 'col_6_error_rate': 0.6695, 'col_7_error_rate': 0.3186, 'col_8_error_rate': 0.1066, 'col_9_error_rate': 0.0986, 'col_13_error_rate': 0.029, 'col_14_error_rate': 0.1739, 'total_error_rate': 0.2395, 'clf_aucroc': 0.862}

Fold 2
Generated incomplete data with missing values for fold 2:
Original data with missing values (subset):
[[nan nan 132870 0 nan 0 0 0 0 0 0 4356 nan nan 0]
 [54 nan 140359 nan 4 nan 1 1 0 0 0 3900 40 0 0]
 [41 0 264663 2 10 2 2 2 nan 0 nan 3900 40 0 0]
 [34 0 216864 0 9 1 3 1 0 0 0 nan 45 0 0]
 [38 0 nan 3 6 2 4 1 0 1 0 3770 40 0 nan]]


100%|███████████████████████████████████████████| 15/15 [00:14<00:00,  1.06it/s]


Completed imputation for fold 2:
X_res with imputed values (subset):
[[41.06108093261719 0 132870 0 8.740769386291504 0 0 0 0 0 0 4356
  46.508544921875 0 0]
 [54 0 140359 0 4 4 1 1 0 0 0 3900 40 0 0]
 [41 0 264663 2 10 2 2 2 0 0 -0.5144968032836914 3900 40 0 0]
 [34 0 216864 0 9 1 3 1 0 0 0 2085.02587890625 45 0 0]
 [38 0 189305.15625 3 6 2 4 1 0 1 0 3770 40 0 0]]
Metrics for this fold: {'nrmse': 0.4443, 'col_1_error_rate': 0.4261, 'col_3_error_rate': 0.3304, 'col_5_error_rate': 0.1455, 'col_6_error_rate': 0.5827, 'col_7_error_rate': 0.1008, 'col_8_error_rate': 0.1022, 'col_9_error_rate': 0.1441, 'col_13_error_rate': 0.0661, 'col_14_error_rate': 0.176, 'total_error_rate': 0.2297, 'clf_aucroc': 0.8961}

Fold 3
Generated incomplete data with missing values for fold 3:
Original data with missing values (subset):
[[82 0 132870 0 9 nan 0 nan nan 0 0 4356 18 0 0]
 [54 0 140359 1 nan 1 1 1 0 0 0 3900 40 0 nan]
 [41 0 264663 2 10 2 2 2 0 0 0 3900 nan 0 0]
 [34 0 216864 0 nan 1 nan 1 0 nan nan

100%|███████████████████████████████████████████| 15/15 [00:14<00:00,  1.04it/s]


Completed imputation for fold 3:
X_res with imputed values (subset):
[[82 0 132870 0 9 1 0 0 0 0 0 4356 18 0 0]
 [54 0 140359 1 9.853012084960938 1 1 1 0 0 0 3900 40 0 0]
 [41 0 264663 2 10 2 2 2 0 0 0 3900 39.67715072631836 0 0]
 [34 0 216864 0 12.405896186828613 1 4 1 0 0 0.0710560753941536 3770 45 0
  0]
 [38 0 150601 3 6 3 1 0 0 1 0 2044.569580078125 40 0 0]]
Metrics for this fold: {'nrmse': 0.4672, 'col_1_error_rate': 0.369, 'col_3_error_rate': 0.2764, 'col_5_error_rate': 0.211, 'col_6_error_rate': 0.7254, 'col_7_error_rate': 0.1636, 'col_8_error_rate': 0.1053, 'col_9_error_rate': 0.1239, 'col_13_error_rate': 0.0789, 'col_14_error_rate': 0.1034, 'total_error_rate': 0.2498, 'clf_aucroc': 0.8794}

Fold 4
Generated incomplete data with missing values for fold 4:
Original data with missing values (subset):
[[82 0 132870 0 9 0 0 0 0 0 0 nan 18 0 0]
 [54 0 140359 1 4 1 1 1 nan 0 0 3900 40 0 nan]
 [41 0 264663 2 10 2 2 nan 0 nan 0 3900 40 0 nan]
 [34 0 216864 0 9 nan 3 1 0 0 nan 3770 45 

100%|███████████████████████████████████████████| 15/15 [00:14<00:00,  1.00it/s]


Completed imputation for fold 4:
X_res with imputed values (subset):
[[82 0 132870 0 9 0 0 0 0 0 0 2142.1455078125 18 0 0]
 [54 0 140359 1 4 1 1 1 0 0 0 3900 40 0 0]
 [41 0 264663 2 10 2 2 0 0 1 0 3900 40 0 1]
 [34 0 216864 0 9 1 3 1 0 0 -0.10445743799209595 3770 45 0 0]
 [38 0 150601 3 7.261241436004639 2 4 0 0 1 0 3770 40 0 0]]
Metrics for this fold: {'nrmse': 0.4574, 'col_1_error_rate': 0.3898, 'col_3_error_rate': 0.3495, 'col_5_error_rate': 0.2039, 'col_6_error_rate': 0.6364, 'col_7_error_rate': 0.1712, 'col_8_error_rate': 0.0331, 'col_9_error_rate': 0.1053, 'col_13_error_rate': 0.024, 'col_14_error_rate': 0.1667, 'total_error_rate': 0.2244, 'clf_aucroc': 0.8505}

Fold 5
Generated incomplete data with missing values for fold 5:
Original data with missing values (subset):
[[nan 0 132870 0 9 0 0 0 0 0 nan 4356 18 0 0]
 [nan 0 140359 1 4 1 1 1 nan nan 0 3900 40 0 0]
 [34 0 216864 0 9 1 3 1 0 0 0 3770 45 0 0]
 [74 nan 88638 4 16 3 2 nan 0 0 0 3683 20 0 nan]
 [68 2 422013 0 9 1 2 0 0 0 

100%|███████████████████████████████████████████| 15/15 [00:13<00:00,  1.08it/s]


Completed imputation for fold 5:
X_res with imputed values (subset):
[[60.28064727783203 0 132870 0 9 0 0 0 0 0 0.801365852355957 4356 18 0 0]
 [43.264129638671875 0 140359 1 4 1 1 1 0 0 0 3900 40 0 0]
 [34 0 216864 0 9 1 3 1 0 0 0 3770 45 0 0]
 [74 0 88638 4 16 3 2 0 0 0 0 3683 20 0 1]
 [68 2 422013 0 9 1 2 0 0 0 0 3683 40.84974670410156 0 0]]
Metrics for this fold: {'nrmse': 0.5503, 'col_1_error_rate': 0.408, 'col_3_error_rate': 0.2803, 'col_5_error_rate': 0.162, 'col_6_error_rate': 0.7248, 'col_7_error_rate': 0.1488, 'col_8_error_rate': 0.1026, 'col_9_error_rate': 0.0574, 'col_13_error_rate': 0.063, 'col_14_error_rate': 0.1405, 'total_error_rate': 0.2258, 'clf_aucroc': 0.8845}
Average nrmse for 15% missing data: 0.48002
Average col_1_error_rate for 15% missing data: 0.37739999999999996
Average col_3_error_rate for 15% missing data: 0.3217
Average col_5_error_rate for 15% missing data: 0.17806
Average col_6_error_rate for 15% missing data: 0.66776
Average col_7_error_rate for 15% mis

100%|███████████████████████████████████████████| 15/15 [00:13<00:00,  1.07it/s]


Completed imputation for fold 1:
X_res with imputed values (subset):
[[41 0 264663 2 10 2 2 2 0 1 0 3900 40 0 0]
 [38 0 150601 3 6 4 4 4 0 1 0 3770 40 0 0]
 [74 1 88638 4 15.927189826965332 4 2 3 0 0 0 3683 20 0 1]
 [68 2 422013 0 10.903552055358887 1 2 0 0 0 -0.42481398582458496
  2124.15625 38.45022201538086 0 0]
 [38 3 164526 5 15 3 0 4 0 1 0 2824 45 0 0]]
Metrics for this fold: {'nrmse': 0.5191, 'col_1_error_rate': 0.3487, 'col_3_error_rate': 0.2738, 'col_5_error_rate': 0.2953, 'col_6_error_rate': 0.7692, 'col_7_error_rate': 0.3653, 'col_8_error_rate': 0.0473, 'col_9_error_rate': 0.1288, 'col_13_error_rate': 0.0694, 'col_14_error_rate': 0.1188, 'total_error_rate': 0.2724, 'clf_aucroc': 0.8607}

Fold 2
Generated incomplete data with missing values for fold 2:
Original data with missing values (subset):
[[82 0 132870 0 nan nan 0 nan 0 0 0 4356 nan 0 0]
 [54 nan 140359 1 nan 1 1 1 0 0 nan 3900 nan nan 0]
 [41 0 264663 2 10 nan 2 2 0 0 nan 3900 40 0 nan]
 [34 0 216864 0 9 1 3 1 0 0 0 3

100%|███████████████████████████████████████████| 15/15 [00:13<00:00,  1.08it/s]


Completed imputation for fold 2:
X_res with imputed values (subset):
[[82 0 132870 0 11.14892292022705 4 0 0 0 0 0 4356 42.29835891723633 0 0]
 [54 0 140359 1 10.313096046447754 1 1 1 0 0 0.3119864761829376 3900
  41.84883499145508 0 0]
 [41 0 264663 2 10 3 2 2 0 0 -0.10126227140426636 3900 40 0 1]
 [34 0 216864 0 9 1 3 1 0 0 0 3770 45 0 0]
 [38 0 155009.15625 3 6 2 4 0 0 1 0 3770 40 0 1]]
Metrics for this fold: {'nrmse': 0.5238, 'col_1_error_rate': 0.362, 'col_3_error_rate': 0.2357, 'col_5_error_rate': 0.1392, 'col_6_error_rate': 0.65, 'col_7_error_rate': 0.1709, 'col_8_error_rate': 0.0952, 'col_9_error_rate': 0.1321, 'col_13_error_rate': 0.0706, 'col_14_error_rate': 0.1714, 'total_error_rate': 0.2253, 'clf_aucroc': 0.8973}

Fold 3
Generated incomplete data with missing values for fold 3:
Original data with missing values (subset):
[[82 0 132870 0 9 0 0 0 nan 0 0 4356 18 0 0]
 [54 0 nan 1 nan 1 1 1 0 0 0 nan 40 0 0]
 [41 0 264663 2 10 2 2 2 0 0 0 nan 40 0 0]
 [34 0 216864 0 9 1 nan 1 

100%|███████████████████████████████████████████| 15/15 [00:13<00:00,  1.09it/s]


Completed imputation for fold 3:
X_res with imputed values (subset):
[[82 0 132870 0 9 0 0 0 0 0 0 4356 18 0 0]
 [54 0 190719.109375 1 8.321946144104004 1 1 1 0 0 0 2050.2861328125 40 0
  0]
 [41 0 264663 2 10 2 2 2 0 0 0 2096.576416015625 40 0 0]
 [34 0 216864 0 9 1 4 1 0 0 0 3770 45 0 0]
 [34.659175872802734 0 150601 3 8.091200828552246 2 4 1 0 1 0 3770 40 0 0]]
Metrics for this fold: {'nrmse': 0.4551, 'col_1_error_rate': 0.306, 'col_3_error_rate': 0.3064, 'col_5_error_rate': 0.2424, 'col_6_error_rate': 0.6347, 'col_7_error_rate': 0.1818, 'col_8_error_rate': 0.0765, 'col_9_error_rate': 0.1465, 'col_13_error_rate': 0.0432, 'col_14_error_rate': 0.1849, 'total_error_rate': 0.2359, 'clf_aucroc': 0.8643}

Fold 4
Generated incomplete data with missing values for fold 4:
Original data with missing values (subset):
[[82 nan 132870 0 nan 0 0 0 0 0 0 4356 nan 0 0]
 [nan 0 140359 1 4 nan 1 1 0 0 0 3900 40 0 0]
 [41 0 nan 2 10 2 2 2 0 0 0 3900 nan nan nan]
 [34 0 216864 0 9 1 3 1 nan 0 0 3770 45

100%|███████████████████████████████████████████| 15/15 [00:14<00:00,  1.02it/s]


Completed imputation for fold 4:
X_res with imputed values (subset):
[[82 0 132870 0 9.851913452148438 0 0 0 0 0 0 4356 32.657283782958984 0 0]
 [45.85426330566406 0 140359 1 4 4 1 1 0 0 0 3900 40 0 0]
 [41 0 154493.859375 2 10 2 2 2 0 0 0 3900 39.72895050048828 0 1]
 [34 0 216864 0 9 1 3 1 0 0 0 3770 45 0 0]
 [38 0 199159.953125 3 6 2 4 0 0 1 0 3770 40 0 0]]
Metrics for this fold: {'nrmse': 0.5788, 'col_1_error_rate': 0.3273, 'col_3_error_rate': 0.3493, 'col_5_error_rate': 0.2875, 'col_6_error_rate': 0.6415, 'col_7_error_rate': 0.1726, 'col_8_error_rate': 0.0643, 'col_9_error_rate': 0.1267, 'col_13_error_rate': 0.0562, 'col_14_error_rate': 0.1418, 'total_error_rate': 0.2378, 'clf_aucroc': 0.8484}

Fold 5
Generated incomplete data with missing values for fold 5:
Original data with missing values (subset):
[[82 0 132870 nan 9 0 0 nan 0 0 0 nan 18 nan nan]
 [54 0 nan 1 4 nan 1 1 0 nan 0 nan 40 0 0]
 [34 nan nan 0 9 1 nan 1 nan 0 0 3770 nan 0 nan]
 [74 1 88638 nan 16 3 2 3 nan 0 nan nan 2

100%|███████████████████████████████████████████| 15/15 [00:14<00:00,  1.03it/s]


Completed imputation for fold 5:
X_res with imputed values (subset):
[[82 0 132870 0 9 0 0 0 0 0 0 2054.958984375 18 0 1]
 [54 0 247192.234375 1 4 4 1 1 0 1 0 2155.4970703125 40 0 0]
 [34 0 241184.921875 0 9 1 4 1 0 0 0 3770 47.14485168457031 0 0]
 [74 1 88638 4 16 3 2 3 0 0 -0.34388917684555054 2008.1453857421875 20 0
  1]
 [68 2 422013 0 9 1 4 0 0 0 0 1996.4923095703125 40 0 0]]
Metrics for this fold: {'nrmse': 0.5286, 'col_1_error_rate': 0.2733, 'col_3_error_rate': 0.3879, 'col_5_error_rate': 0.2917, 'col_6_error_rate': 0.6923, 'col_7_error_rate': 0.1657, 'col_8_error_rate': 0.046, 'col_9_error_rate': 0.1677, 'col_13_error_rate': 0.06, 'col_14_error_rate': 0.1718, 'total_error_rate': 0.2438, 'clf_aucroc': 0.878}
Average nrmse for 20% missing data: 0.52108
Average col_1_error_rate for 20% missing data: 0.32345999999999997
Average col_3_error_rate for 20% missing data: 0.31062
Average col_5_error_rate for 20% missing data: 0.25122
Average col_6_error_rate for 20% missing data: 0.67754

In [ ]:
[38 nan 150601 3 6 nan 4 1 0 1 0 3770 nan 0 0]]
[74 1 88638 4 16 3 2 3 0 0 0 3683 20 0 1]
[41 0 264663 2 10 3 2 2 0 0 0 3900 40 0 0]
[41 0 264663 2 10 nan nan 2 0 0 nan 3900 40 0 0]
[41 0 264663 2 10 4 2 2 0 0 0.42824387550354004 3900 40 0 0